// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'game': string;
  'winner': string;
}
export const cssExports: CssExports;
export default cssExports;
