version: "3.8"

services:
  app:
    image: docker.io/ynonp/theboard:1.0
    env_file: ./env/k8s.env
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"

    secrets:
      - dbpassword

  db:
    image: docker.io/ynonp/theboard-db:1.0
    secrets:
      - dbpassword
    env_file: ./env/k8s.env
    ports:
      - "5432:5432"

    volumes:
      - data:/pgdata

secrets:
  dbpassword:
    file: ./secrets/db_password


volumes:
  data:
